### ISSUE TITLE
Worker should return the repo link along with the badges.

### ISSUE THREAD

**Issue by argonlaser** [scriptnull/badgeit#14]
As per our discussion, the HTTP request ```https://badgeit-front.com/callback``` sent to the front service requires repo link along the array of possible badges something like this:

```
{
    "repoLink": "https://github.com/argonlaser/badgeit-front",
     "badges": [<array of badges>]
}
```
This info shall be used to send the badges to all the clients listening to the room(repoLink).

**Comment by scriptnull** [comment]
@argonlaser, I am going to name the field as "Remote" while sending it back. As its the naming convention that we use while sending it to the API.

**Comment by scriptnull** [comment]
Also changing the label fom bug to enhancement, as it does not even exists in our system yet. I think it would be good to have bug label to denote regressions and wrong usage of things.

**Comment by scriptnull** [comment]
This change was deployed few hours back. the name of the field should be "remote"
