### ISSUE TITLE
Add semaphore CI badge. 

### ISSUE THREAD

**Issue by argonlaser** [scriptnull/badgeit#20]

**Comment by argonlaser** [comment]
https://semaphoreci.com/argonlaser/badgeit-front/settings/badge

**Comment by scriptnull** [comment]
This should be really straight forward. We already have Travis and Circle in place. The code should be very similar to them. Feel free to pick up.

**Comment by scriptnull** [comment]
starting to work on this

**Comment by scriptnull** [comment]
This is done.

Could be verified by visiting http://badgeit.today/w/https://github.com/argonlaser/badgeit-front
